services:
  - type: web
    name: maintenance-tracker
    plan: starter
    buildCommand: |
      composer install --no-dev --optimize-autoloader --no-interaction
      composer require symfony/runtime
      npm install
      npx encore production
    startCommand: apache2-foreground
    runtime: docker