services:
  - type: web
    name: maintenance-tracker
    env: docker
    plan: free
    autoDeploy: true
    buildCommand: ""
    startCommand: ""
    envVars:
      - key: APP_ENV
        value: prod
      - key: APP_DEBUG
        value: "0"
      - key: APP_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: maintenance-db

databases:
  - name: maintenance-db
    plan: free
    databaseName: app
    user: app
